#!/bin/sh
#
# Auto-run VirtIO magic number test on boot
#

case "$1" in
  start)
        echo "Starting VirtIO Magic Number Test..."
        /root/test_virtio_magic.sh
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
